name: Lint workflows

on:
  workflow_call:
    inputs:
      torch_rbln_sha:
        description: Git commit SHA
        type: string
        required: true
    secrets:
      GIT_PAT:
        description: Personal access token
        required: true

permissions:
  contents: read

defaults:
  run:
    shell: bash

jobs:
  lint_workflows:
    name: Lint workflows
    if: ${{ github.repository_owner == vars.TORCH_RBLN_REPO_OWNER }}
    runs-on: ${{ vars.TORCH_RBLN_RUNNER_CPU_SMALL }}
    env:
      GIT_CONFIG_COUNT: '1'
      GIT_CONFIG_KEY_0: safe.directory
      GIT_CONFIG_VALUE_0: ${{ github.workspace }}
    timeout-minutes: 15
    container:
      image: ghcr.io/rebellions-sw/rbln-test:0.11.0-ubuntu22.04-py3.12
      credentials:
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GIT_PAT }}
    steps:
      - name: Check out repository
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10  # v6.0.3
        with:
          ref: ${{ inputs.torch_rbln_sha }}
          persist-credentials: false

      - name: Install uv
        uses: astral-sh/setup-uv@fac544c07dec837d0ccb6301d7b5580bf5edae39  # v8.2.0

      - name: Install dependencies
        run: |
          set -euo pipefail

          uv venv
          uv pip install --group lint

      - name: Run actionlint
        run: |
          set -euo pipefail

          uv run --no-sync actionlint

      - name: Run yamllint
        run: |
          set -euo pipefail

          uv run --no-sync yamllint --strict .github/

      - name: Run zizmor
        run: |
          set -euo pipefail

          uv run --no-sync zizmor --offline .github/
