name: CD

on:
  push:
    tags: [v*]

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.sha }}
  cancel-in-progress: false

jobs:
  dispatch_torch_rbln_cd:
    uses: ./.github/workflows/_dispatch-event.yaml
    with:
      event_name: ${{ github.event_name }}
      event_type: torch-rbln-cd
      torch_rbln_ref: ${{ github.ref }}
      torch_rbln_sha: ${{ github.sha }}
    secrets:
      GIT_PAT: ${{ secrets.GIT_PAT }}
