name: Pre-merge checks

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  lint:
    uses: ./.github/workflows/_lint.yaml
    with:
      torch_rbln_sha: ${{ github.event.pull_request.head.sha }}
      python_versions: '["3.12"]'
      build_types: '["Release"]'
      base_revision: ${{ github.event.pull_request.base.sha }}
    secrets:
      GIT_PAT: ${{ secrets.GIT_PAT }}
      HARBOR_USERNAME: ${{ secrets.HARBOR_USERNAME }}
      HARBOR_PASSWORD: ${{ secrets.HARBOR_PASSWORD }}
      NEXUS_USERNAME: ${{ secrets.NEXUS_USERNAME }}
      NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
      RBLN_INDEX_USERNAME: ${{ secrets.RBLN_INDEX_USERNAME }}
      RBLN_INDEX_PASSWORD: ${{ secrets.RBLN_INDEX_PASSWORD }}

  dispatch_event:
    uses: ./.github/workflows/_dispatch-event.yaml
    with:
      event_name: ${{ github.event_name }}
      event_type: torch-rbln-ci
      torch_rbln_ref: ${{ github.event.pull_request.head.ref }}
      torch_rbln_sha: ${{ github.event.pull_request.head.sha }}
    secrets:
      GIT_PAT: ${{ secrets.GIT_PAT }}
