name: Release

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [main]
  push:
    branches: [main]

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name == 'pull_request' && github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

jobs:
  dispatch_torch_rbln_release:
    if: ${{ github.repository_owner == vars.TORCH_RBLN_REPO_OWNER }}
    uses: ./.github/workflows/_dispatch-event.yaml
    with:
      event_name: ${{ github.event_name }}
      event_type: torch-rbln-release
      torch_rbln_ref: ${{ github.event_name == 'pull_request' && github.event.pull_request.head.ref || github.ref }}
      torch_rbln_sha: ${{ github.event_name == 'pull_request' && github.event.pull_request.head.sha || github.sha }}
    secrets:
      GIT_PAT: ${{ secrets.GIT_PAT }}
